version: '3'
services:
    application:
        image: bacemmehri1/test_technique
        container_name: test_technique
        ports:
            - 80:8080
        links:
            - redis
    redis:
        image: redis:latest
        container_name: redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379
volumes:
    redis-data: